CREATE TABLE [dbo].[Meals]
(
	[Id] INT NOT NULL IDENTITY (1,1),
    [MealNumber] INT NOT NULL, 
    [DayId] INT NOT NULL

	CONSTRAINT [PK_Meals] PRIMARY KEY CLUSTERED ([Id] ASC), 
	CONSTRAINT FK_Meals_Days FOREIGN KEY (DayId) REFERENCES [Days] (Id)
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_MEALS_X ON dbo.Meals (MealNumber, DayId)