CREATE TABLE [dbo].[Days]
(
	[Id] INT NOT NULL IDENTITY (1,1),
    [Date] DATETIME NOT NULL

	CONSTRAINT [PK_Days] PRIMARY KEY CLUSTERED ([Id] ASC)
)
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_Days_Created ON dbo.[Days] (Date)